# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 07:56
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('first_name', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('surname', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('biography', wagtail.wagtailcore.blocks.RichTextBlock()))),
        ),
    ]
