# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 07:56
from __future__ import unicode_literals

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='body',
            field=wagtail.core.fields.StreamField((('first_name', wagtail.core.blocks.CharBlock(required=True)),
                                                   ('surname', wagtail.core.blocks.CharBlock(required=True)),
                                                   ('biography', wagtail.core.blocks.RichTextBlock()))),
        ),
    ]
