# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:02
from __future__ import unicode_literals

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170905_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='body',
            field=wagtail.core.fields.StreamField((('person', wagtail.core.blocks.StructBlock((('name',
                                                                                                wagtail.core.blocks.CharBlock()),
                                                                                               ('height',
                                                                                                wagtail.core.blocks.DecimalBlock()),
                                                                                               ('age',
                                                                                                wagtail.core.blocks.IntegerBlock())))),)),
        ),
    ]
