# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170905_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sub_heading', models.TextField()),
                ('sub_sub_heading', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='body',
            field=models.TextField(),
        ),
    ]
