# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170905_0820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeHeading',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='body',
        ),
        migrations.AddField(
            model_name='resumepage',
            name='name',
            field=models.TextField(default='Name Surname'),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='sub_heading',
            field=models.TextField(default='Highly trained monkey'),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='sub_sub_heading',
            field=models.TextField(default='Also a programmer'),
        ),
    ]
