# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:50
from __future__ import unicode_literals

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0006_auto_20170905_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepagesection',
            name='page',
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogpagegalleryimage',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='blogpagetag',
            options={},
        ),
        migrations.AlterModelOptions(
            name='blogtagindexpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resumepage',
            options={},
        ),
        migrations.AddField(
            model_name='resumepage',
            name='contact_me',
            field=wagtail.core.fields.RichTextField(default='+37400000000'),
        ),
        migrations.DeleteModel(
            name='ResumePageSection',
        ),
    ]
