# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 08:58
from __future__ import unicode_literals

import wagtail.core.blocks
import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_auto_20170905_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='contact_me',
            field=wagtail.core.fields.StreamField((('text_and_code', wagtail.core.blocks.StructBlock(((
                                                                                                                    'text',
                                                                                                                    wagtail.core.blocks.TextBlock()),
                                                                                                      (
                                                                                                                    'code',
                                                                                                                    wagtail.core.blocks.TextBlock())))),)),
        ),
    ]
