# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 07:13
from __future__ import unicode_literals

import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0009_auto_20170905_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepagerelatedtextandcode',
            name='page',
        ),
        migrations.AddField(
            model_name='resumepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('id',
                                                                                                               wagtail.wagtailcore.blocks.CharBlock()),
                                                                                                              (
                                                                                                              'content',
                                                                                                              wagtail.wagtailcore.blocks.RichTextBlock())))),),
                                                         blank=True),
        ),
        migrations.DeleteModel(
            name='ResumePageRelatedTextAndCode',
        ),
    ]
