# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:36
from __future__ import unicode_literals

import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0011_auto_20170907_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section', wagtail.wagtailcore.blocks.StructBlock((('id',
                                                                                                               wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                   blank=True)),
                                                                                                              ('title',
                                                                                                               wagtail.wagtailcore.blocks.CharBlock()),
                                                                                                              (
                                                                                                              'content',
                                                                                                              wagtail.wagtailcore.blocks.StreamBlock(
                                                                                                                  ((
                                                                                                                   'rich_text',
                                                                                                                   wagtail.wagtailcore.blocks.RichTextBlock(
                                                                                                                       blank=True)),
                                                                                                                   (
                                                                                                                   'h3_block',
                                                                                                                   wagtail.wagtailcore.blocks.StructBlock(
                                                                                                                       (
                                                                                                                       (
                                                                                                                       'id',
                                                                                                                       wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                           blank=True)),
                                                                                                                       (
                                                                                                                       'title',
                                                                                                                       wagtail.wagtailcore.blocks.CharBlock()),
                                                                                                                       (
                                                                                                                       'content',
                                                                                                                       wagtail.wagtailcore.blocks.StreamBlock(
                                                                                                                           (
                                                                                                                           (
                                                                                                                           'rich_text',
                                                                                                                           wagtail.wagtailcore.blocks.RichTextBlock(
                                                                                                                               blank=True)),
                                                                                                                           (
                                                                                                                           'h4_block',
                                                                                                                           wagtail.wagtailcore.blocks.StructBlock(
                                                                                                                               (
                                                                                                                               (
                                                                                                                               'id',
                                                                                                                               wagtail.wagtailcore.blocks.CharBlock(
                                                                                                                                   blank=True)),
                                                                                                                               (
                                                                                                                               'title',
                                                                                                                               wagtail.wagtailcore.blocks.CharBlock()),
                                                                                                                               (
                                                                                                                               'content',
                                                                                                                               wagtail.wagtailcore.blocks.StreamBlock(
                                                                                                                                   (
                                                                                                                                   (
                                                                                                                                   'rich_text',
                                                                                                                                   wagtail.wagtailcore.blocks.RichTextBlock(
                                                                                                                                       blank=True)),)))),
                                                                                                                               blank=True)))))),
                                                                                                                       blank=True)))))))),),
                                                         blank=True),
        ),
    ]
