# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0015_auto_20170911_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='heading',
            field=models.TextField(default='Heading'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='sub_heading',
            field=models.TextField(default='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='sub_sub_heading',
            field=models.TextField(default='Sub Sub Heading'),
        ),
    ]
