# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0017_auto_20170911_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='sub_heading',
            field=models.TextField(blank=True, default='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='blogindexpage',
            name='sub_sub_heading',
            field=models.TextField(blank=True, default='Sub Sub Heading'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='sub_heading',
            field=models.TextField(blank=True, default='Sub Heading'),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='sub_sub_heading',
            field=models.TextField(blank=True, default='Sub Sub Heading'),
        ),
    ]
