# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 11:11
from __future__ import unicode_literals

import django.db.models.deletion
import wagtail.wagtailcore.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('blog', '0019_auto_20170911_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('heading', models.TextField(default='Heading')),
                ('sub_heading', models.TextField(blank=True, default='Sub Heading')),
                ('sub_sub_heading', models.TextField(blank=True, default='Sub Sub Heading')),
                ('content', wagtail.wagtailcore.fields.StreamField(())),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='intro',
        ),
    ]
