# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 11:36
from __future__ import unicode_literals

import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0022_auto_20170913_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField(
                (('home_page_card_block', wagtail.wagtailcore.blocks.RichTextBlock()),)),
        ),
    ]
