# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:27
from __future__ import unicode_literals

import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0023_auto_20170913_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('link_blocks', wagtail.wagtailcore.blocks.StructBlock(((
                                                                                                                  'page',
                                                                                                                  wagtail.wagtailcore.blocks.PageChooserBlock()),
                                                                                                                  (
                                                                                                                  'content',
                                                                                                                  wagtail.wagtailcore.blocks.RichTextBlock())))),)),
        ),
    ]
