# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-15 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0024_auto_20170913_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogindexpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='blogindexpage',
            name='sub_sub_heading',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='sub_sub_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sub_sub_heading',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='sub_heading',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='sub_sub_heading',
        ),
    ]
