# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-08 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('blog', '0028_blogpage_date_default_now'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPage',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='BlogIndex',
        ),
        migrations.RenameModel(
            old_name='HomePage',
            new_name='Home',
        ),
        migrations.RemoveField(
            model_name='resumepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='ResumePage',
        ),
    ]
