# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_rename_page_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
