---
- hosts: babken.org
  remote_user: root
  tasks:
  - name: update homepage git repo to latest master (HEAD) version from github
    git: repo=https://github.com/axper/homepage.git dest=/srv/http/homepage version=HEAD
  - name: ensure nginx package is at the latest version
    apt: name=nginx state=latest
  - name: ensure supervisor package is at the latest version
    apt: name=supervisor state=latest
  - name: django collect static files to root static directory
    django_manage: virtualenv=/root/.virtualenvs/homepage app_path=/srv/http/homepage command=collectstatic
  - name: link nginx.conf to nginx's config dir in /etc
    file: src=/srv/http/homepage/deploy/nginx.conf dest=/etc/nginx/sites-enabled/homepage.conf state=link
  - name: link supervisor.conf to supervisor's config dir in /etc
    file: src=/srv/http/homepage/deploy/supervisor.conf dest=/etc/supervisor/conf.d/homepage.conf state=link
  - name: restart supervisor service
    service: name=supervisor state=restarted enabled=yes
  - name: restart nginx and make sure it's enabled
    service: name=nginx state=restarted enabled=yes
